const wco = {
    0: ["Clear Sky", "clear"],
    1: ["Mainly Clear, partly cloudy, and overcast", "clear"],
    2: ["Mainly Clear, partly cloudy, and overcast", "clear"],
    3: ["Mainly Clear, partly cloudy, and overcast", "clear"],
    45: ["Fog and depositing rime fog", "fog"],
    48: ["Fog and depositing rime fog", "fog"],
    51: ["Drizzle: Light, moderate, and dense intensity", "drizzle"],
    53: ["Drizzle: Light, moderate, and dense intensity", "drizzle"],
    55: ["Drizzle: Light, moderate, and dense intensity", "drizzle"],
    56: ["Freezing Drizzle: Light and dense intensity", "drizzle"],
    57: ["Freezing Drizzle: Light and dense intensity", "drizzle"],
    61: ["Rain: Slight, moderate and heavy intensity", "rain"],
    63: ["Rain: Slight, moderate and heavy intensity", "rain"],
    65: ["Rain: Slight, moderate and heavy intensity", "rain"],
    66: ["Freezing Rain: Light and heavy intensity", "rain"],
    67: ["Freezing Rain: Light and heavy intensity", "rain"],
    71: ["Snow fall: Slight, moderate, and heavy intensity", "snow"],
    73: ["Snow fall: Slight, moderate, and heavy intensity", "snow"],
    75: ["Snow fall: Slight, moderate, and heavy intensity", "snow"],
    77: ["Snow grains", "snow"],
    80: ["Rain showers: Slight, moderate, and violent", "rain"],
    81: ["Rain showers: Slight, moderate, and violent", "rain"],
    82: ["Rain showers: Slight, moderate, and violent", "rain"],
    85: ["Snow showers slight and heavy", "snow"],
    86: ["Snow showers slight and heavy", "snow"],
  };
  
  export default wco;